path: "_secrets"
default: # default is testing (aka staging) environment
  secrets:
    - ".env"
    - "Src/GoogleService-Info.plist"    

sets:
  production:
    path: "_production"
  ci:
    path: "_ci"
    secrets:
      - "Src/FirebaseTestLab-ServiceAccount.json"
output: "secrets_cici"