path: "_secrets"
default: # default is testing (aka staging) environment
  secrets:
    - ".env"
    - "Src/GoogleService-Info.plist"

sets:
  production:
    path: "_production"
output: "secrets_cici"