osx_image: xcode12.2
language: swift

cache:
  bundler: true
  cocoapods: true
  npm: true

podfile: Podfile

before_install:
  - gem install cici
  
before_script:
  - cici decrypt --set ci
  - ./set_environment.sh 

env:
  global:
    - UI_TESTS_DEVICE_ID="iphone11" # Device model ID. `gcloud beta firebase test ios models list`
    - UI_TESTS_IOS_VERSION="13.6"   # iOS version ID. `gcloud beta firebase test ios models list`
    - GOOGLE_APPLICATION_CREDENTIALS="Src/FirebaseTestLab-ServiceAccount.json" # path to the service account key file to authenticate with firebase service account. Readme talks about this. 
    # Below are secret environment variables you need to set. 
    # Note: You need to escape all of the special characters. Add a `\` character before each. 
    # 
    # MATCH_GIT_REPO="git@github.com/owner/repo.git" - github repo to store the match repo information
    # MATCH_PASSWORD= password to decrypt secrets made by Fastlane match
    # FASTLANE_USER= email address to the Apple ID account to use to login to fastlane. This is also your apple email address. 
    # FASTLANE_PASSWORD= password to the Apple ID account used to login for fastlane.
    # GITHUB_TOKEN= personal access token where github username has push access to the repo to make comments and releases. 
    # FIREBASE_DISTRIBUTION_APP_ID= firebase app id for app you want to use for firebase app distribution. 
    # FIREBASE_TOKEN="123" - token to login to Firebase account that is added to Firebase project. Get token with `bundle exec fastlane run firebase_app_distribution_login` https://firebase.google.com/docs/app-distribution/ios/distribute-fastlane#step_2_authenticate_with_firebase
    # APPLE_DEVELOPER_ACCOUNT_TEAM_ID="12345" - team that the app belongs to. Get from Apple Developer Center for account FASTLANE_USER logged in as. 
    # APPLE_DEVELOPER_ACCOUNT_TEAM_NAME="Team name" - team that the app belongs to. Get from Apple Developer Center for account FASTLANE_USER logged in as. 
    # APP_STORE_CONNECT_TEAM_NAME="Team name" - team name found in App Store Connect. https://stackoverflow.com/a/46415415/1486374
    # APP_STORE_CONNECT_TEAM_ID="12345" - team id found in App Store Connect. https://stackoverflow.com/a/46415415/1486374
    # CODECOV_TOKEN - codecov.io token for repository. Used for test coverage. Make sure code coverage is enabled in XCode https://github.com/codecov/example-swift#produce-coverage-reports
    # FIREBASE_PROJECT_ID - Found in Firebase project > Settings > General. 

jobs:
  include:    
  - stage: tests
    script:
      - set -e
      - npm i @commitlint/travis-cli @commitlint/config-conventional && npx commitlint-travis
      - bundle exec fastlane unit_test && bash <(curl -s https://codecov.io/bash) 
      - bundle exec fastlane ui_test
  - stage: pr
    script:
      - set -e
      - ./set_environment.sh && bundle exec fastlane qa_deploy
  - stage: deploy
    script: 
      - set -e 
      - npm i @semantic-release/git @semantic-release/github @semantic-release/changelog @semantic-release/exec && npx semantic-release
  - stage: cron
    script:
      - set -e
      - ./set_environment.sh testing && bundle exec fastlane refresh_dsyms
      - ./set_environment.sh production && bundle exec fastlane refresh_dsyms

stages:
  - name: tests
    if: type IN (push, pull_request) AND tag IS blank
  - name: pr
    if: type IN (pull_request) 
  - name: deploy
    if: type IN (push) AND branch IN (master, beta)
  - name: cron
    if: type IN (cron)
