os: osx
osx_image: xcode11.2
language: swift

cache:
  bundler: true 
  cocoapods: true
  
before_install:
  - gem install cocoapods
  - pod --version
  - pod repo update
install:  
  - bundle install
  - pod install 
  - brew update 
  - brew install imagemagick  # for fastlane frameit 
  - brew install librsvg graphicsmagick # for fastlane generating app icons
env:
  global:
    # Below are secret environment variables you need to set. 
    # Note: You need to escape all of the special characters. Add a `\` character before each. 
    # 
    # MATCH_PASSWORD= password to decrypt secrets made by Fastlane match
    # FASTLANE_PASSWORD= password to the Apple ID account used to login for fastlane.
    # DANGER_GITHUB_API_TOKEN= personal github oauth token for Danger bot. https://danger.systems/guides/getting_started.html#setting-up-an-access-token    
    #### IAM account. SNS topic sending, S3 bucket uploading. 
    # AWS_IAM_ACCESS_KEY=12345
    # AWS_IAM_ACCESS_SECRET=1234
    # AWS_S3_BUCKET_NAME_TEST_RESULTS=name-of-bucket
    # AWS_S3_BUCKET_PATH_TEST_RESULTS=test_results
    # AWS_SNS_APP_UPDATE_TOPIC=arn:aws:sns:us-east-1:38383839494:app-deployed-notifier
    # AWS_SNS_DEV_TOPIC=arn:aws:sns:us-east-1:38383839494:app-developers-notifier    
    AWS_REGION=us-east-1

jobs:
  include:
  - stage: commit
    script:
      - ruby scripts/tests.rb
  - stage: pr
    script:
      - ruby scripts/tests.rb 
      - bundle exec danger --fail-on-errors=true
  - stage: deploy
    script: rm .env; cp secrets/production/.env .env; ./set_environment.rb; bundle exec fastlane deploy
  - stage: cron
    script: 
      - rm .env; cp secrets/production/.env .env; ./set_environment.rb; bundle exec fastlane refresh_dsyms;

stages:
  - name: pr
    if: type IN (pull_request)
  - name: commit
    if: type IN (push) AND tag IS blank
  - name: deploy
    if: tag IS present  
  - name: cron
    if: type IN (cron)
