os: osx
osx_image: xcode11.2
language: swift

cache:
  bundler: true 
  cocoapods: true
  
before_install:
  - gem install cocoapods
  - pod --version
  - pod repo update
install:  
  - bundle install
  - pod install 
env:
  global:
    # Below are secret environment variables you need to set. 
    # Note: You need to escape all of the special characters. Add a `\` character before each. 
    # 
    # MATCH_PASSWORD= password to decrypt secrets made by Fastlane match
    # FASTLANE_PASSWORD= password to the Apple ID account used to login for fastlane.
    # DANGER_GITHUB_API_TOKEN= personal github oauth token for Danger bot. https://danger.systems/guides/getting_started.html#setting-up-an-access-token

jobs:
  include:
  - stage: commit
    script:
      - bundle exec fastlane scan
  - stage: pr
    script:       
      - bundle exec fastlane scan
      - bundle exec danger --fail-on-errors=true 
  - stage: deploy
    script: bundle exec fastlane deploy
  - stage: maintenance
    script: bundle exec fastlane maintenance

stages:
  - name: pr
    if: type IN (pull_request)
  - name: commit
    if: type IN (push) AND tag IS blank
  - name: deploy
    if: tag IS present  
  - name: maintenance
    if: type IN (cron)
